install.packages("tidyverse")
library(tidyverse)
names <- c("Rajeev", "Soniya", "Sarthak", "Priyanka")
age <- c(58L, 52L , 22L ,19L )
people <- data.frame(names, age)
head(people)
str(people)
glimpse(people)
colnames(people)
mutate(people, age_in_20 = age + 20)